server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Elpeluche0323/pep2-milkstgo
          search-paths: /config-data
  application:
    name: config-service